# Generated by Django 6.0.3 on 2026-03-12 04:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menu',
            old_name='invertory',
            new_name='inventory',
        ),
    ]
